### ISSUE TITLE
Swope analysis fails when running over a dataset containing molecules with multiple 3 letter company codes

### ISSUE THREAD

**Issue by ldamore** [openforcefield/openff-benchmark#101]
From the csv files it can be seen that molecules from different companies are wrongly being compared.

qm_min,mm_conf,mm_min,rmsd (mm_conf/qm_min),dE (mm_conf-mm_min)
JNS-01356-07,BRI-01356-07,BRI-01356-08,, 6.84774323e+00
JNS-01356-07,BRI-01356-02,BRI-01356-08,, 9.72582731e+00
JNS-01356-07,BRI-01356-04,BRI-01356-08,, 1.41296403e+00
JNS-01356-07,BRI-01356-03,BRI-01356-08,, 3.09150186e+00
JNS-01356-07,BRI-01356-01,BRI-01356-08,, 1.25368682e+01
JNS-01356-07,BRI-01356-05,BRI-01356-08,, 7.29534843e+00
JNS-01356-07,BRI-01356-00,BRI-01356-08,, 3.39467115e+00
JNS-01356-07,BRI-01356-06,BRI-01356-08,, 8.77350580e+00

Note: not tested yet, however `lucas` analysis may exhibit the same wrong behaviour.

**Comment by dotsdl** [comment]
Closed by #102.
