### ISSUE TITLE
Add heuristic check for connectivity changes in molecules post-QM

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/openff-benchmark#60]
It is sometimes (in practice, rarely) the case that atoms move around during QM optimization, and in this case creating an `openff.toolkit.toplogy.Molecule` could result in a molecule with coordinates mismatched on the wrong atoms. 

The OpenFF `Molecule` object is created from the original CMILES attached to the `QCElemental.models.Molecule` (QCE `Molecule`) prior to the optimization, but the final geometry of the molecule, though always the same array size and shape, may have an ordering different than the starting geometry due to atom movements. This would proceed silently with the current implementation of creating an OpenFF `Molecule` from a QCE `Molecule`.

We need a way to identify these cases upon creating an OpenFF `Molecule`, and throwing appropriate exceptions and/or warnings. @jthorton has a heuristic he has put into [`openff-qcsubmit`](https://github.com/openforcefield/openff-qcsubmit/blob/ce2df12d60ec01893e77cbccc50be9f0944a65db/openff/qcsubmit/results.py#L769). It may also be possible to do checks on atom element identity matching against the CMILES-generated OpenFF `Molecule` and the QCE `Molecule` the geometry is being extracted from.

**Comment by dotsdl** [comment]
@jthorton noted that order of atoms is actually maintained by QCE `Molecule` even if atoms moved around, so the problem really comes down to interpreting connectivity for the OpenFF `Molecule`. This is difficult to do generally, but a filtering heuristic like the one he has proposed may be our best option in the interim.

**Comment by j-wags** [comment]
Closed by #65
