### ISSUE TITLE
Make Boron-containing molecules fail out of workflow in coverage report

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-benchmark#67]
Bill Swope reported that a boron-containing molecule was failing in the MM energy evaluation step. I don't think this should have made it through the coverage reporting step. This issue can be closed once the coverage reporting step filters out molecules containing Boron (or other missing parameters).

**Comment by j-wags** [comment]
@jthorton was unable to reproduce this issue. When Josh tried, the boron-containing molecule was filtered out by the coverage report step when it ran `create_openmm_system`. Josh notes that his test was for a single conformer, it's possible that a multi-conformer molecule would have a different behavior.

**Comment by dotsdl** [comment]
Ian Craig also reported that silicon-containing molecules made it through to optimization as well. I'm not sure if we expect this?

**Comment by j-wags** [comment]
Oof, nope. We shouldn't have parameters for silicon either (Cmd-F `#14` in [`openff-1.3.0`](https://github.com/openforcefield/openff-forcefields/blob/2855e9fd81e768e2d53dbe898fda7e42b869bbd7/openforcefields/offxml/openff-1.3.0.offxml#L1) returns 0 hits). So let's make sure our instructions for running the SMARTS filter will remove boron, silicon, and iodine-containing molecules.
