### ISSUE TITLE
Workflow Component : Identifier assignment

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/openff-benchmark#8]
Implemented in `openff.benchmark.utils`. Can be as simple as a function that takes as input group/company code (3-letter), all molecules (with predefined conformers, if present). Will then produce a mapping of identifiers to molecule objects as:  COM-XXXXX-YY
- three-letter company code (COM)
- molecule-index (XXXXX)
- numerical conformer-index (YY); 01, 02, 03,…

Note that with this approach, each molecule submitted in the dataset will have exactly one conformer. We would not be stacking multiple conformers into each Molecule.

**Comment by j-wags** [comment]
This step will:
* strip out all non-essential information from inputs (SD tags and such).
* provide a record/mapping of input files to assigned IDs so subsequent steps can read it
