### ISSUE TITLE
Workflow Component : Conformer generation

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/openff-benchmark#9]
For molecules with fewer than 10 conformers predefined, additional conformers will be generated to give a total of 10. This can already be done with `openforcefield.topology.Molecule.generate_conformers`. 

We will need the mapping from **Identifier assignment** #8 after this, so it likely makes sense to switch the order of these workflow components.

**Comment by jthorton** [comment]
Here is the workflow module in QCSubmit that should help with this https://github.com/openforcefield/qcsubmit/blob/5d1a3303ff2e5313b5b20ebc55333ec30d5e31b3/qcsubmit/workflow_components/conformer_generation.py#L12

**Comment by j-wags** [comment]
Specification notes:
* Can use QCSubmit tool for this
* Conformers should be "unpacked" into separate molecules

**Comment by dotsdl** [comment]
Output files from this step (or #8 if swapped): SDF files with ID as filename.

**Comment by dotsdl** [comment]
@j-wags please close if you consider this feature complete.
